### ISSUE TITLE
JS-main page 

### ISSUE THREAD

**Issue by gwengibbes** [gwengibbes/com6338-module10-assignment10-gibbes-longo-avery#20] opened 2023-11-13 22:30 UTC
Call the API to get the list of food pairings based on the selected wine

**Comment by ElodieLongo** [comment] 2023-11-13 23:31
Thank you Gwen, here we should check together because I am not sure how you want to do this as I had a slightly different thing in mind. See my other comments on this topic.

**Comment by gwengibbes** [comment] 2023-11-13 23:33
Can you make the time suggested tomorrow to meet? Let’s discuss then.
I think changing things at this last minute is going to make things harder.
Either way we must meet asap.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ElodieLongo** [comment] 2023-11-16 16:28
Closing since this is a duplicate of issue #1

**Closed as completed by ElodieLongo** 2023-11-16 16:28 UTC
Labels: To do
